version: '3.8'
services:
  mysql:
    build:
      context: ./db
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: [ "--secure-file-priv=", "--loose-local-infile=1", "--local-infile=1" ]
    ports:
      - "${MYSQL_PORT}:3306"
